"""
   Module covers iOS screens' elements
"""
all_editfields = 'XCUIElementTypeTextField'
all_buttons = 'XCUIElementTypeButton'
all_textviews = 'XCUIElementTypeStaticText'
all_pickwheels = 'XCUIElementTypePickerWheel'
all_otherviews = 'XCUIElementTypeOther'
all_textview_type = 'XCUIElementTypeTextView'
screen_heading_title = 'title_text'

# LANDING SCREEN
password_field = 'XCUIElementTypeSecureTextField'
landing_logo_image = 'logo_image'
landing_heading_text = 'heading_text'
landing_search_title ='search_title_text'
landing_explore_search_textfield = 'explore_courses_textfield'
landing_searh_result_title = 'title_text'
landing_back_button = 'back_button'
landing_discover_title = 'Search results'
logistration_register_button = 'logistration_register_button'
logistration_signin_button = 'logistration_signin_button'
register_screen_title = 'register_text'
notification_allow_button = 'Allow'

# SIGN IN SCREEN
signin_text = 'signin_text'
signin_welcome_text = 'welcome_back_text'
signin_username_text = 'username_text'
signin_username_textfield = 'username_textfield'
signin_password_text = 'password_text'
signin_password_textfield = 'password_textfield'
signin_forgot_password_button = 'forgot_password_button'
signin_button = 'signin_button'
signin_social_auth_title_text = 'social_auth_title_text'
signin_social_auth_google_button = 'social_auth_google_button'
signin_social_auth_facebook_button = 'social_auth_facebook_button'
sigin_social_auth_microsoft_button = 'social_auth_microsoft_button'
signin_social_auth_apple_button = 'social_auth_apple_button'

# FORGOT PASSWORD SCREEN
forgot_title_text = 'forgot_title_text'
forgot_description_text = 'forgot_description_text'
forgot_email_text = 'email_text'
forogt_email_textfield = 'email_textfield'
forgot_reset_password_button = 'reset_password_button'
forgot_check_email_image = 'check_email_image'
forgot_recover_title_text = 'recover_title_text'
forgot_recover_description_text = 'recover_description_text'
forgot_check_email_image = 'check_email_image'
forgot_recover_title_text = 'recover_title_text'
forgot_recover_description_text = 'recover_description_text'

# REGISTER SCREEN
register_screen_heading = 'register_text'
register_signup_text = 'signup_text'
register_signup_subtitle_text = 'signup_subtitle_text'
register_name_text = 'name_text'
register_name_textfield = 'name_textfield'
register_name_instructions_text = 'name_instructions_text'
register_username_text = 'username_text'
register_username_textfield = 'username_textfield'
register_username_instructions_text = 'username_instructions_text'
register_email_text = 'email_text'
register_email_textfield = 'email_textfield'
register_email_instructions_text = 'email_instructions_text'
register_password_text = 'password_text'
register_password_textfield = 'password_textfield'
register_password_instructions_text = 'password_instructions_text'
register_country_text = 'country_text'
register_country_picker_button = 'country_picker_button'
register_country_instructions_text = 'country_instructions_text'
register_terms_of_service_link = 'Terms of Service and Honor Code'
register_privacy_policy_link = 'Privacy Policy'
register_show_optional_fields = 'optional_fields_text'
register_signup_button = 'signup_button'
register_social_auth_title_text = 'social_auth_title_text'
register_country_picker_title = 'picker_title_text'
register_picker_search_textfield = 'picker_search_textfield'
register_picker_accept_button = 'picker_accept_button'

# WHATS NEW SCREEN
whats_new_screen_title = 'What\'s New'
whats_new_msg_title = 'title_text'
whats_new_description = 'description_text'
whats_new_btn_next = 'next_button'
whats_new_btn_prev = 'previous_button'

# MAIN DASHBOARD SCREEN
main_dashboard_discover_tab = 'Discover'
main_dashboard_programs_tab = 'Programs'
main_dashboard_profile_tab = 'Profile'
main_dashboard_tab = 'Dashboard'
