"""
   Module covers iOS screens' elements
"""
all_editfields = 'XCUIElementTypeTextField'
all_buttons = 'XCUIElementTypeButton'
all_textviews = 'XCUIElementTypeStaticText'
all_pickwheels = 'XCUIElementTypePickerWheel'
all_otherviews = 'XCUIElementTypeOther'
all_textview_type = 'XCUIElementTypeTextView'
screen_heading_title = 'title_text'
back_button_navigation = 'back_button'
navigation_bar_title = 'XCUIElementTypeNavigationBar'

# LANDING SCREEN
password_field = 'XCUIElementTypeSecureTextField'
landing_logo_image = 'logo_image'
landing_heading_text = 'heading_text'
landing_search_title ='search_title_text'
landing_explore_search_textfield = 'explore_courses_textfield'
landing_searh_result_title = 'title_text'
landing_back_button = 'back_button'
landing_discover_title = 'Search results'
logistration_register_button = 'logistration_register_button'
logistration_signin_button = 'logistration_signin_button'
register_screen_title = 'register_text'
notification_allow_button = 'Allow'
landing_explore_courses_button = 'explore_courses_button'

# SIGN IN SCREEN
signin_text = 'signin_text'
signin_welcome_text = 'welcome_back_text'
signin_username_text = 'username_text'
signin_username_textfield = 'username_textfield'
signin_password_text = 'password_text'
signin_password_textfield = 'password_textfield'
signin_forgot_password_button = 'forgot_password_button'
signin_button = 'signin_button'
signin_social_auth_title_text = 'social_auth_title_text'
signin_social_auth_google_button = 'social_auth_google_button'
signin_social_auth_facebook_button = 'social_auth_facebook_button'
sigin_social_auth_microsoft_button = 'social_auth_microsoft_button'
signin_social_auth_apple_button = 'social_auth_apple_button'

# FORGOT PASSWORD SCREEN
forgot_title_text = 'forgot_title_text'
forgot_description_text = 'forgot_description_text'
forgot_email_text = 'email_text'
forogt_email_textfield = 'email_textfield'
forgot_reset_password_button = 'reset_password_button'
forgot_check_email_image = 'check_email_image'
forgot_recover_title_text = 'recover_title_text'
forgot_recover_description_text = 'recover_description_text'
forgot_check_email_image = 'check_email_image'
forgot_recover_title_text = 'recover_title_text'
forgot_recover_description_text = 'recover_description_text'

# REGISTER SCREEN
register_screen_heading = 'register_text'
register_signup_text = 'signup_text'
register_signup_subtitle_text = 'signup_subtitle_text'
register_name_text = 'name_text'
register_name_textfield = 'name_textfield'
register_name_instructions_text = 'name_instructions_text'
register_username_text = 'username_text'
register_username_textfield = 'username_textfield'
register_username_instructions_text = 'username_instructions_text'
register_email_text = 'email_text'
register_email_textfield = 'email_textfield'
register_email_instructions_text = 'email_instructions_text'
register_password_text = 'password_text'
register_password_textfield = 'password_textfield'
register_password_instructions_text = 'password_instructions_text'
register_country_text = 'country_text'
register_country_picker_button = 'country_picker_button'
register_country_instructions_text = 'country_instructions_text'
register_terms_of_service_link = 'Terms of Service and Honor Code'
register_privacy_policy_link = 'Privacy Policy'
register_show_optional_fields = 'optional_fields_text'
register_signup_button = 'signup_button'
register_social_auth_title_text = 'social_auth_title_text'
register_country_picker_title = 'picker_title_text'
register_picker_search_textfield = 'picker_search_textfield'
register_picker_accept_button = 'picker_accept_button'
register_search = 'Search'

# WHATS NEW SCREEN
whats_new_screen_title = 'What\'s New'
whats_new_msg_title = 'title_text'
whats_new_description = 'description_text'
whats_new_btn_next = 'next_button'
whats_new_btn_prev = 'previous_button'

# MAIN DASHBOARD SCREEN
main_dashboard_discover_tab = 'Discover'
main_dashboard_programs_tab = 'Programs'
main_dashboard_profile_tab = 'Profile'
main_dashboard_tab = 'Dashboard'
main_dashboard_learn_tab = 'Learn'
main_dashboard_dropdown_text = 'dropdown_menu_text'

#  MY COURSES LIST SCREEN
my_courses_header_text = 'courses_header_text'
my_courses_welcomeback_text = 'courses_welcomeback_text'
my_course_image = 'course_image'
my_course_org_text = 'edX'
my_course_name_text = 'Infinity test course'
my_course_end_text = 'course_end_text'
my_course_arrow_image = 'arrow_image'
my_course_item_list = 'course_item'
all_courses_header_text = 'all_courses_header_text'
all_courses_label = 'All'
all_courses_inprogress_label = 'In Progress'
all_courses_completed_label = 'Completed'
all_courses_expired_label = 'Expired'

# PROFILE SCREEN
profile_screen_title = 'Profile'
profile_edit_button = 'edit_profile_button'
profile_user_avatar_image = 'user_avatar_image'
profile_user_name_text = 'user_name_text'
profile_user_username_text = 'user_username_text'
profile_settings_text = 'settings_text'
profile_video_settings_button = 'video_settings_button'
profile_manage_account_label = 'Manage Account'
profile_dates_calendar_label = 'Dates & Calendar'
profile_support_info_text = 'support_info_text'
profile_tos_text = 'Terms of use'
profile_privacy_policy = 'privacy_policy'
profile_cookies_policy = 'cookies_policy'
profile_dont_sell_data = 'dont_sell_data'
profile_contact_support = 'Contact support'
profile_view_faq = 'view_faq'
profile_version_info = 'version_info'
profile_logout_button = 'logout_button'
profile_settings_button = 'settings'
manage_account_title = 'manage_account_text'

# LOGOUT DIALOGUE
logout_close_button = 'Close'
logout_dialog_title = 'Are you sure you want to log out?'
logout_button = 'Log out'

# COURSE DASHBOARD SCREEN
my_courses_course_item = 'course_item'
course_dashboard_resources_tab = 'org.edx.mobile:id/resources'
course_dashboard_course_tab = 'Home'
course_dashboard_videos_tab = 'Videos'
course_dashboard_discussions_tab = 'Discussions'
course_dashboard_dates_tab = 'Dates'
course_dashboard_more_tab = 'More'

# DISCOVERY SCREEN
discovery_back_button = 'Start'
discovery_search_field = 'XCUIElementTypeSearchField'
discovery_search_button = 'Search'
