"""
   Module covers Android screens' elements
"""

all_images = 'android.widget.ImageView'
all_image_buttons = 'android.widget.ImageButton'
all_textviews = 'android.widget.TextView'
all_listviews = 'android.widget.FrameLayout'
back_button_navigation = 'ib_back'
txt_toolbar_title = 'txt_toolbar_title'

# LOGISTRATION SCREEN
landing_screen_title = 'txt_screen_title'
landing_search_label = 'txt_search_label'
landing_discovery_search = 'tf_search'
landing_explore_courses_button = 'txt_explore_all_courses'
landing_register_button = 'btn_register'
landing_signin_button = 'btn_sign_in'
back_button = 'btn_back'
signin_title = 'txt_sign_in_title'

# LOGIN SCREEN
sign_in_title = 'txt_sign_in_title'
sign_in_description = 'txt_sign_in_description'
sign_in_email_label = 'txt_email_label'
sign_in_tf_email = 'tf_email'
sign_in_password_label = 'txt_password_label'
sign_in_tf_password = 'tf_password'
sign_in_forgot_password = 'txt_forgot_password'
google_auth_button = 'btn_google_auth'
facebook_auth_button = 'btn_facebook_auth'
microsoft_auth_button = 'btn_microsoft_auth'

# FORGOT PASSWORD SCREEN
forgot_password_title = 'txt_forgot_password_title'
forgot_password_description = 'txt_forgot_password_description'
forgot_password_reset_button = 'btn_reset_password'

# REGISTER SCREEN
register_back_button = 'ib_back'
register_txt_sign_up_title = 'txt_sign_up_title'
register_txt_description = 'txt_sign_up_description'
register_txt_name_label = 'txt_name_label'
register_tf_name = 'tf_name'
register_txt_name_description = 'txt_name_description'
register_txt_username_label = 'txt_username_label'
register_tf_username = 'tf_username'
register_txt_username_description = 'txt_username_description'
register_txt_email_label = 'txt_email_label'
register_tf_email = 'tf_email'
register_txt_email_description = 'txt_email_description'
register_txt_password_label = 'txt_password_label'
register_tf_password = 'tf_password'
register_txt_password_description = 'txt_password_description'
register_txt_country_label = 'txt_country_label'
register_tf_country = 'tf_country'
register_txt_country_description = 'txt_country_description'
register_txt_honor_code = 'txt_honor_code'
register_txt_optional_field = 'txt_optional_field'
register_btn_create_account = 'btn_create_account'
register_education_level = 'txt_level_of_education_label'
register_education_level_placeholder = 'txt_level_of_education_placeholder'
register_gender_label = 'txt_gender_label'
register_gender_label_placeholder = 'txt_gender_placeholder'
register_country_selection_dialogue = 'txt_selection_title'
register_txt_US_title = 'txt_us_title'
register_country_sb_search = 'sb_search'
txt_google_auth = 'txt_google_auth'
txt_facebook_auth = 'txt_facebook_auth'
txt_microsoft_auth = 'txt_microsoft_auth'
main_dashboar_home_tab = 'org.edx.mobile:id/navigation_bar_item_large_label_view'

# WHATS NEW SCREEN
whats_new_screen_title = 'What\'s New'
whats_new_close_button = 'ib_close'
whats_new_msg_title = 'txt_whats_new_title'
whats_new_description = 'txt_whats_new_description'
whats_new_btn_next = 'btn_next'
whats_new_btn_prev = 'btn_prev'
whats_new_done_button = 'txt_done'

# MAIN DASHBOARD SCREEN
main_dashboard_fragment_discover = 'org.edx.mobile:id/fragmentDiscover'
main_dashboard_fragment_learn = 'org.edx.mobile:id/fragmentLearn'
main_dashbaord_fragment_profile = 'org.edx.mobile:id/fragmentProfile'

# MY COURSES LIST SCREEN
my_course_toolbar_title = 'txt_toolbar_title'
my_course_screen_title = 'txt_courses_title'
my_courses_description = 'txt_courses_description'
my_courses_org_name = 'txt_course_org'
my_courses_course_name = 'txt_course_name'
my_courses_course_date = 'txt_course_date'
my_courses_course_item = 'btn_course_item'

# PROFILE SCREEN
profile_screen_title = 'txt_profile_title'
profile_edit_button = 'txt_edit'
profile_img_profile = 'img_profile'
profile_txt_name = 'txt_profile_name'
profile_username = 'txt_profile_username'
profile_txt_settings = 'txt_settings'
profile_txt_video_settings = 'txt_video_settings'
profile_txt_support_info = 'Support'
profile_txt_contact_support = 'Contact Support'
profile_txt_terms_of_use = 'Terms of Use'
profile_txt_privacy_policy = 'Privacy Policy'
profile_txt_cookie_policy = 'Cookie policy'
profile_personal_info = 'Do not sell my personal information'
profile_txt_view_faq = 'View FAQ'
profile_app_version_code = 'Version: 6.0.1'
profile_txt_up_to_date = 'Up-to-date'
profile_txt_logout = 'Log Out'
profile_settings_txt = 'Settings'
profile_manage_account_label = 'Manage Account'
profile_video_label = 'Video'
profile_dates_calendar_label = 'Dates & Calendar'

# LOGOUT DIALOGUE
logout_close_button = 'ib_close'
logout_dialog_title = 'txt_logout_dialog_title'
logout_button = 'txt_logout'

# EDIT PROFILE SCREEN
edit_profile_title = 'txt_edit_profile_title'
edit_profile_leave_button = 'txt_leave'
edit_profile_button = 'txt_edit_profile'

# COURSE DASHBOARD SCREEN
course_dashboard_more_tab = 'More'
course_dashboard_home_tab = 'Home'
course_dashboard_videos_tab = 'Videos'
course_dashboard_discussions_tab = 'Discussions'
course_dashboard_dates_tab = 'Dates'
permission_icon = 'com.android.permissioncontroller:id/permission_icon'
permission_title = 'com.android.permissioncontroller:id/permission_message'
permission_allow_button = 'com.android.permissioncontroller:id/permission_allow_button'
permission_dont_allow_button = 'com.android.permissioncontroller:id/permission_deny_button'
