"""
All strings accessible in Pages & Tests
"""

ANDROID = "Android"
IOS = "iOS"
LOGIN = "Sign in"
RESULTS_DIRECTORY = "results"
HTML_REPORT_FILE_NAME = ".html"
LOG_FILE_NAME = "report.log"
BLANK_FIELD = ""
ERROR = "Problem, "
ERROR_SETTING_CAPS = "Problem, setting environment specific caps"
ERROR_UTF_ELEMENT = "Unable to find specific element - "
TRUE_LOWERCASE = "true"
FALSE_LOWERCASE = "false"
ANDROID_APP_VERSION = "Version: 6.0.7"
IOS_APP_VERSION = "Version: 6.0.4, Up-to-date"
IOS_SELECTED_TAB_VALUE = "1"

# Exception Messages
VERIFICATION_FAILED_ERROR = "Failed to verify {0}. Expected {1}, Found {2}"

# LANDING SCREEN
LANDING_MESSAGE = "Courses and programs from the world's best universities in your pocket."
LANDING_SEARCH_TITLE = "What do you want to learn?"
LANDING_SEARCH_COURSES = "Search our 3000+ courses"
DISCOVER_SCREEN_HEADING = "Discover"
ERROR_SCREEN_NOT_LOADED = "Problem, screen is not loaded."
LANDING_EXLPORE_COURSES = "Explore all courses"
LANDING_SEARCH_RESULTS_TITLE = "Search"
LANDING_LOGO_IMAGE = "appLogo"
LANDING_BACK_BUTTON = "Back"
DISCOVERY_SCREEN_TITLE = "Explore the catalog"

# SIGN IN SCREEN
SIGN_IN_MESSAGE = "Welcome back! Sign in to access your courses."
EMAIL_OR_USERNAME = "Email or Username"
EMAIL_OR_USERNAME_IOS = "Email or username"
PASSWORD = "Password"
GOOGLE_SIGNIN = "Continue with: Google"
FACEBOOK_SIGNIN = "Continue with: Facebook"
MICROSOFT_SIGNIN = "Continue with: Microsoft"
APPLE_SIGNIN = "Continue with: Apple"
BACK_BUTTON = "Start"
BACK_BUTTON_SMALL = "back"
SOCIAL_AUTH_TITLE = "Or sign in with:"
GOOGLE_SIGNIN_ANDROID = "Sign in with Google"
FACEBOOK_SIGNIN_ANDRIOD = "Sign in with Facebook"
MICROSOFT_SIGNIN_ANDROID = "Sign in with Microsoft"

# REGISTER SCREEN
REGISTER = "Register"
REGISTER_SIGN_UP_HEADING = "Sign up"
REGISTER_CREATE_ACCOUNT_MESSAGE = "Create an account to start learning today!"
REGISTER_FULL_NAME_TITLE = "Full Name"
REGISTER_FULL_NAME_MESSAGE = "This name will be used on any certificates that you earn."
REGISTER_PUBLIC_USERNAME_TITLE = "Public Username"
REGISTER_PUBLIC_USERNAME_MESSAGE = "The name that will identify you in your courses. It cannot be changed later."
REGISTER_EMAIL_TITLE = "Email"
REGISTER_EMAIL_MESSAGE = "This is what you will use to login."
REGISTER_PASSWORD_TITLE = "Password"
REGISTER_PASSWORD_MESSAGE = "Your password must contain at least 8 characters, including 1 letter & 1 number."
REGISTER_HONOR_POLICY_TEXT = (
    "By creating an account, you agree to the edX End User Licence Agreement and edX Terms of Service and Honor Code"
    " and you acknowledge "
    "that edX and each Member process your personal data in accordance with the edX Privacy Policy."
)
REGISTER_COUNTRY_TITLE = "Country or Region of Residence"
REGISTER_COUNTRY_MESSAGE = "The country or region where you live."
REGISTER_SHOW_OPTIONAL_FIELDS = "optional_fields_text"
REGISTER_CREATE_ACCOUNT_BUTTON = "signup_button"
REGISTER_OPTIONS_TITLE = "Continue with:"
REGISTER_GOOGLE_SIGNUP = "Continue with: Google"
REGISTER_FACEBOOK_SIGNUP = "Continue with: Facebook"
REGISTER_MICROSOFT_SIGNUP = "Continue with: Microsoft"
REGISTER_APPLE_SIGNUP = "Continue with: Apple"
REGISTER_COUNTRY_PICKER_TITLE = "Country or Region of Residence"
REGISTER_COUNTRY = "United States of America"
REGISTER_COUNTRY_SEARCH_FIELD = "Search"
REGISTER_COUNTRY_ACCEPT_BUTTON = "Accept"
REGISTER_PASSWORD_ERROR = (
    "This password is too common. This password is too short. "
    "It must contain at least 8 characters. This password must contain at least 1 number."
)
REGISTER_COUNTRY_SELECT = "United States of America"
REGISTER_ERROR_FULL_NAME = "Enter your full name"
REGISTER_ERROR_USER_NAME = "Username must be between 2 and 30 characters long."
REGISTER_ERROR_EMAIL = "Enter a valid email address that contains at least 3 characters."
REGISTER_ERROR_PASSWORD = (
    "This password is too short. It must contain at least 8 characters. "
    "This password must contain at least 1 letter. This password must contain at least 1 number."
)
REGISTER_ERROR_SELECT_COUNTRY = "Select your country or region of residence"
REGISTER_EDUCATION_LEVEL = "Highest level of education completed"
REGISTER_EDUCATION_LEVEL_PLACEHOLDER = "Highest level of education completed"
REGISTER_GENDER_LABEL = "Gender"
GOOGLE_AUTH_TEXT = "Continue with Google"
FACEBOOK_AUTH_TEXT = "Continue with Facebook"
MICROSOFT_AUTH_TEXT = "Continue with Microsoft"

# FORGOT PASSWORD SCREEN
FORGOT_PASSWORD = "Forgot password?"
FORGOT_PASSWORD_TITLE = "Forgot password"
FORGOT_DESCRIPTION_TEXT = (
    "Please enter your log-in or recovery email address below and we will send you an email with instructions."
)
FORGOT_EMAIL_TITLE = "Email"
RESET_PASSWORD_BUTTON = "Reset password"
FORGOT_CHECK_EMAIL_IMAGE = "checkEmail"
FORGOT_RECOVER_TITLE_TEXT = "Check your email"
FORGOT_RECOVER_DESCRIPTION = "We have sent a password recover instructions to your email"
FORGOT_PASSWORD_EMAIL_ERROR = "Please enter your e-mail address and try again."

# WHATS NEW SCREEN
WHATS_NEW_TITLE = "What's New"
WHATS_NEW_CLOSE_BUTTON = "Close"
WHATS_NEW_NEXT_BUTTON = "Next"

# MAIN DASHBOARD SCREEN
MAIN_DASHBOARD_DASHBOARD_TAB = "Dashboard"
MAIN_DASHBOARD_PROGRAMS_TAB = "Programs"
MAIN_DASHBOARD_PROFILE_TAB = "Profile"
MAIN_DASHBOARD_COURSES = "Courses"
MAIN_DASHBOARD_LEARN_TAB = "Learn"
MAIN_DASHBOARD_COURSE_DESCRIPTION = "View All My Courses "

# PROFILE SCREEN
PROFILE_SCREEN_TITLE = "Profile"
PROFILE_EDIT_BUTTON = "Edit"
PROFILE_EDIT_BUTTON_IOS = "edit"
PROFILE_IMAGE_TEXT = "Test automation user profile image"
PROFILE_NAME_TEXT = "Test automation user"
PROFILE_USERNAME_TEXT = "@Automation_User_007"
PROFILE_SETTINGS_TEXT = "settings"
PROFILE_SETTINGS_UPPER_TEXT = "Settings"
PROFILE_VIDEO_SETTINGS = "Video settings"
PROFILE_SUPPORT = "Support"
PROFILE_SUPPORT_INFO = "Support info"
PROFILE_CONTACT_SUPPORT = "contact support"
PROFILE_TERMS_OF_USE = "Terms of use"
PROFILE_TERMS_OF_USE_UPPERCASE = "Terms of Use"
PROFILE_PRIVACY_POLICY = "privacy policy"
PROFILE_COOKIE_POLICY = "cookie policy"
PROFILE_PERSONAL_INFO = "Do not sell my personal information"
PROFILE_FAQ = "View FAQ"
PROFILE_APP_UP_TO_DATE = "Up-to-date"
PROFILE_LOGOUT_BUTTON = "Log Out"
PROFILE_MANAGE_ACCOUNT = "Manage Account"
PROFILE_DATES_CALENDAR = "Dates & Calendar"
PROFILE_MANAGE_ACCOUNT_LABEL = "Manage Account"
PROFILE_VIDEO_LABEL = "Video"
PROFILE_DATES_CALENDAR_LABEL = "Dates & Calendar"
RTESTER_PROFILE_IMG_TEXT = "rtester99 profile image"
RTESTER_NAME_TEXT = "rtester99"
RTESTER_USERNAME_TEXT = "@rtester99"

# EDIT PROFILE
EDIT_PROFILE_TYPE_LABEL = "Limited profile"
EDIT_PROFILE_USER_IMAGE = "test-mobile-automation profile image"
EDIT_PROFILE_USER_NAME = "Test automation user"
EDIT_PROFILE_MESSAGE = "Your profile information is only visible to you. Only your username is visible to others."
EDIT_PROFILE_LOCATION_LABEL = "Location"
EDIT_PROFILE_LOCATION = "United States"
EDIT_PROFILE_EMAIL_LABEL = "Email"
EDIT_PROFILE_LANGUAGE_LABEL = "Spoken Language"
EDIT_PROFILE_LANGUAGE_PLACEHOLDER = "Spoken Language"
EDIT_PROFILE_ABOUT_ME_LABEL = "About Me"
EDIT_PROFILE_ABOUT_ME = "About Me"

# LOG OUT
LOGOUT_DIALOG_TITLE = "Are you sure you want to log out?"

# EDIT PROFILE SCREEN
EDIT_PROFILE_TITLE = "Edit Profile"
EDIT_PROFILE_TITLE_IOS = "Edit profile"
EDIT_PROFILE_LEAVE_BUTTON = "Leave"
EDIT_PROFILE_DONE_BUTTON = "Done"

# MY COURSES LIST SCREEN
MY_COURSES_SECOND_COURSE_NAME = "DemoX"
MY_COURSES_ARROW_IMAGE_TEXT = "arrowRight16"
MAIN_DASHBOARD_COURSE_ORG = "edX"
MAIN_DASHBOARD_COURSE_NAME = "Infinity test course"
MAIN_DASHBOARD_RESUME_LABEL = "Resume Course"
MAIN_DASHBOARD_ALL_COURSES_LABEL = "View All My Courses"
ALL_COURSES_HEADER_LABEL = "All My Courses"
ALL_COURSES_LABEL = "All"
ALL_COURSES_INPROGRESS_LABEL = "In Progress"
ALL_COURSES_COMPLETED_LABEL = "Completed"
ALL_COURSES_EXPIRED_LABEL = "Expired"
MY_COURSES_ALL_COURSES_LABEL = "All Courses"
MY_COURSES_ALL_ENROLLED_LABEL = "All"
MY_COURSES_IN_PROGRESS_LABEL = "In Progress"
MY_COURSES_COMPLETED_LABEL = "Completed"
MY_COURSES_EXPIRED_LABEL = "Expired"

# COURSE DASHBOARD SCREEN
COURSE_DASHBOARD_HOME_TAB = "Home"
COURSE_DASHBOARD_RESOURCES_TAB = "Handouts"
COURSE_DASHBOARD_VIDEOS_TAB = "Videos"
COURSE_DASHBOARD_DISCUSSIONS_TAB = "Discussions"
COURSE_DASHBOARD_DATES_TAB = "Dates"
COURSE_DASHBOARD_MORE_TAB = "More"

# DISCOVERY SCREEN
DISCOVERY_SCREEN_HEADING = "Explore the catalog"
DISCOVERY_SCREEN_MESSAGE = "Build skills. Earn a certificate. Advance your career."
DISCOVERY_SEARCH_FIELD_HINT = "What do you want to learn?"
DISCOVERY_SEARCH_BUTTON = "Search"
DISCOVERY_TRENDING_LABEL = "Trending:"
DISCOVERY_TRENDING_LABEL_IOS = "Trending"
DISCOVERY_TRENDING_COURSE_PYTHON = "Python"
DISCOVERY_TRENDING_COURSE_EXCEL = "Excel"
DISCOVERY_TRENDING_COURSE_DATA = "Data Sciences"
DISCOVERY_TRENDING_COURSE_MARKETING = "Marketing"
DISCOVERY_MAIN_CONTENT = "Content"
DISCOVERY_SEARCH_BREADCRUMB = "breadcrumb"
DISCOVERY_SEARCH_BREADCRUMB_IOS = "breadcrumb, navigation"
DISCOVERY_FILTER_BY_POPULAR_COURSES = "Filter by popular subjects"
DISCOVERY_FIRST_POPULAR_COURSE = "Data Science"
DISCOVERY_SECOND_POPULAR_COURSE = "Computer Science"
DISCOVERY_AI_CHAT_CLOSE_BUTTON = "Close proactive message"
DISCOVERY_ENGINEERING_POPULAR_COURSE = "Engineering"
DISCOVERY_POPULAR_MATH_COURSE = "Math"
DISCOVERY_MATH_RESULTS = "5552 results"
DISCOVERY_MATH_RESULTS_BUTTON = "Show (204)"
DISCOVERY_MATH_PAGINATION_RESULTS = "204 results"
DISCOVERY_PAGINATION_TEXT = "pagination"
DISCOVERY_PAGINATION_TEXT_IOS = "pagination, navigation"
DISCOVERY_DEMOX_COURSE = "DemoX edX Course"

# COURSE HOME TAB SCREEN
COURSE_MISSED_DEADLINES_LABEL = "Missed some deadlines?"
COURSE_DEADLINE_DESCRIPTION_LABEL = (
    "Don't worry - shift our suggested schedule to complete past due assignments without losing any progress."
)
COURSE_SHIFT_DUE_DATES = "Shift due dates"
COURSE_RESUME_WITH_LABEL = "Resume with:"
COURSE_CONTINUE_WITH_LABEL = "Continue with:"
COURSE_RESUME_BUTTON = "Resume"
COURSE_SECTION_LABEL = "Introduction"
COURSE_SUBSECTION_LABEL = "Welcome to an edX Course!"
COURSE_SECTION_1_LABEL = "Module 1: Experiencing Course Content"
COURSE_SUBSECTION_1_LABEL = "Lesson 1: edX Content Basics"
COURSE_COMPONENT_LABEL = "Homework 1: Your First Grade"
COURSE_COMPONENT_NEXT_BUTTON = "Next"
COURSE_COMPONENT_PREVIOUS_BUTTON = "Prev"
COURSE_COMPONENT_FINISH_BUTTON = "Finish"
COURSE_COMPLETION_BACK_BUTTON = "Back to outline"
