"""
All strings accessible in Pages & Tests
"""

ANDROID = 'Android'
IOS = 'iOS'
LOGIN = 'Sign in'
RESULTS_DIRECTORY = 'results'
LOG_FILE_NAME = 'report.log'
BLANK_FIELD = ''
ERROR = 'Problem, '
ERROR_SETTING_CAPS = 'Problem, setting environment specific caps'
ERROR_UTF_ELEMENT = 'Unable to find specific element - '
TRUE_LOWERCASE = 'true'

# LANDING SCREEN
LANDING_MESSAGE = 'Welcome to edX'
LANDING_MESSAGE_IOS = 'Courses and programs from the world\'s best universities in your pocket.'
LANDING_SEARCH_TITLE = 'What do you want to learn?'
LANDING_SEARCH_COURSES = 'Search our 3000+ courses'
DISCOVER_SCREEN_HEADING = 'Discover'
ERROR_SCREEN_NOT_LOADED = 'Problem, screen is not loaded.'
LANDING_EXLPORE_COURSES = 'Explore all courses'
LANDING_SEARCH_RESULTS_TITLE = 'Search'
LANDING_LOGO_IMAGE = 'appLogo'
LANDING_BACK_BUTTON = 'arrowLeft'

# SIGN IN SCREEN
SIGN_IN_MESSAGE = 'Welcome back! Please authorize to continue.'
EMAIL_OR_USERNAME = 'Email or username'
PASSWORD = 'Password'
GOOGLE_SIGNIN = 'Sign in with Google'
FACEBOOK_SIGNIN = 'Sign in with Facebook'
MICROSOFT_SIGNIN = 'Sign in with Microsoft'
APPLE_SIGNIN = 'Sign in with Apple'
BACK_BUTTON = 'Back'
SOCIAL_AUTH_TITLE = 'Or sign in with:'

# REGISTER SCREEN
REGISTER = 'Register'
REGISTER_SIGN_UP_HEADING = 'Sign up'
REGISTER_CREATE_ACCOUNT_MESSAGE = 'Create new account.'
REGISTER_FULL_NAME_TITLE = 'Full Name'
REGISTER_FULL_NAME_MESSAGE = 'This name will be used on any certificates that you earn.'
REGISTER_PUBLIC_USERNAME_TITLE = 'Public Username'
REGISTER_PUBLIC_USERNAME_MESSAGE = 'The name that will identify you in your courses. It cannot be changed later.'
REGISTER_EMAIL_TITLE = 'Email'
REGISTER_EMAIL_MESSAGE = 'This is what you will use to login.'
REGISTER_PASSWORD_TITLE = 'Password'
REGISTER_PASSWORD_MESSAGE = 'Your password must contain at least 8 characters, including 1 letter & 1 number.'
REGISTER_COUNTRY_TITLE = 'Country or Region of Residence'
REGISTER_COUNTRY_MESSAGE = 'The country or region where you live.'
REGISTER_SHOW_OPTIONAL_FIELDS = 'optional_fields_text'
REGISTER_CREATE_ACCOUNT_BUTTON = 'signup_button'
REGISTER_OPTIONS_TITLE = 'Or register with:'
REGISTER_GOOGLE_SIGNUP = 'Register with Google'
REGISTER_FACEBOOK_SIGNUP = 'Register with Facebook'
REGISTER_MICROSOFT_SIGNUP = 'Register with Microsoft'
REGISTER_APPLE_SIGNUP = 'Register with Apple'
REGISTER_COUNTRY_PICKER_TITLE = 'Country or Region of Residence'
REGISTER_COUNTRY_SEARCH_FIELD = 'Search'
REGISTER_COUNTRY_ACCEPT_BUTTON = 'Accept'
REGISTER_PASSWORD_ERROR = 'This password is too common. This password is too short. It must contain at least 8 characters. This password must contain at least 1 number.'
REGISTER_COUNTRY_SELECT = 'United States of America'
# FORGOT PASSWORD SCREEN
FORGOT_PASSWORD = 'Forgot password?'
FORGOT_PASSWORD_TITLE = 'Forgot password'
FORGOT_DESCRIPTION_TEXT = 'Please enter your log-in or recovery email address below and we will send you an email with instructions.'
FORGOT_EMAIL_TITLE = 'Email'
RESET_PASSWORD_BUTTON = 'Reset password'
FORGOT_CHECK_EMAIL_IMAGE = 'checkEmail'
FORGOT_RECOVER_TITLE_TEXT = 'Check your email'
FOROGT_RECOVER_DESCRIPTION = 'We have sent a password recover instructions to your email'
